name: request-new-term
description: Template to submit a new device to the SeaVoX Device Catalogue (L22)
title: "NTR: "
labels: [New term]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please provide the following information (all fields are mandatory unless specified otherwise). If you are unsure about a particular field, please either make an attempt or leave it blank. Queries can be discussed in the ticket comments.

  - type: input
    id: make
    attributes:
      label: Device make
      description: >
        Name of the manufacturer or institution which made the instrument. 
        If unknown or generic, input 'n/a' or 'Unspecified'.

  - type: input
    id: range
    attributes:
      label: Device range (if applicable)
      description: >
        The manufacturer's instrument model range (e.g. WindObserver). 
        If there is no official model range, input 'n/a'.

  - type: input
    id: model
    attributes:
      label: Device model
      description: >
        Name of the instrument model. If there is no official model name, input 'n/a'.

  - type: input
    id: version
    attributes:
      label: Model version (if applicable)
      description: >
        Sub-model/version name (e.g. 'D', 'v3.2'). If none, input 'n/a'.

  - type: input
    id: alt_name
    attributes:
      label: Model alternative name (if applicable)
      description: >
        E.g. Glider Payload CTD alternative name is GPCTD. If none, input 'n/a'.

  - type: input
    id: modification
    attributes:
      label: Modification (if applicable)
      description: >
        Describe any modifications. If none, input 'n/a'.

  - type: input
    id: qualification
    attributes:
      label: Qualification (if applicable)
      description: >
        Further describe instrument type (e.g. 'portable', 'automated'). If none, input 'n/a'.

  - type: input
    id: instrument_type
    attributes:
      label: Instrument type
      description: >
        What type of instrument is this (e.g. global positioning system, fluorometer, radiometer)?
        See [L05 SeaDataNet device categories](https://vocab.nerc.ac.uk/collection/L05/current/) for reference.

  - type: dropdown
    id: describes
    attributes:
      label: Instrument category?
      description: >
        Does the term describe an individual instrument, a system, a series of instruments, or none of the above? 
        See [this guidance](https://github.com/nvs-vocabs/Guides-and-Resources/blob/main/Instruments%20and%20Sensors.md) for the differences between instrument series and systems.
      options:
        - Individual
        - System
        - Series

  - type: input
    id: reference
    attributes:
      label: Reference (if applicable)
      description: >
        Citation for the instrument (e.g. Hall and Bumpus, 1937). Leave blank if none.

  - type: input
    id: short_name
    attributes:
      label: Short name
      description: >
        Usually a shortened version of name, or an alternative name.

  - type: input
    id: documentation
    attributes:
      label: Documentation
      description: >
        Link to journal reference, manufacturer data sheet, website, manual, etc.
      
  - type: markdown
    attributes:
      value: "## Optional"

  - type: textarea
    id: mapping
    attributes:
      label: "Mapping to external terminologies"
      description: "If your submission relates to existing terms in external resources, please enter one or a list of URIs"

  - type: input
    id: term-utilisation
    attributes:
      label: "Term utilisation"
      description: |
            Please provide the project, activity, or context associated with this request, 
            and a brief indication of how or where it will be used. e.g.,  
            EMODnet Chemistry – dataset submission to SeaDataNet;  
            R2R Catalogue - online data portal;  
            ONC - online data portal;  
            LandSeaLOT – new sensor addition to SCOOP catalogue
      
  - type: input
    id: orcid
    attributes:
      label: "ORCID"
      description: "Optionally provide your ORCID identifier"
      placeholder: "0000-0000-0000-0000"
