name: request-new-term
description: Template to submit a new device to the SeaVoX Device Catalogue (L22)
title: "NTR:"
labels: [New term]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please provide the following information (all fields are mandatory unless specified otherwise)

  - type: input
    id: make
    attributes:
      label: Device make
      description: >
        Name of the manufacturer or institution which made the instrument. 
        If unknown or generic, input 'n/a' or 'Unspecified'.

  - type: input
    id: range
    attributes:
      label: Device range (if applicable)
      description: >
        The manufacturer's instrument model range (e.g. WindObserver). 
        If there is no official model range, input 'n/a'.

  - type: input
    id: model
    attributes:
      label: Device model
      description: >
        Name of the instrument model. If there is no official model name, input 'n/a'.

  - type: input
    id: version
    attributes:
      label: Model version (if applicable)
      description: >
        Sub-model/version name (e.g. 'D', 'v3.2'). If none, input 'n/a'.

  - type: input
    id: alt_name
    attributes:
      label: Model alternative name (if applicable)
      description: >
        E.g. Glider Payload CTD alternative name is GPCTD. If none, input 'n/a'.

  - type: input
    id: modification
    attributes:
      label: Modification (if applicable)
      description: >
        Describe any modifications. If none, input 'n/a'.

  - type: input
    id: qualification
    attributes:
      label: Qualification (if applicable)
      description: >
        Further describe instrument type (e.g. 'portable', 'automated'). If none, input 'n/a'.

  - type: input
    id: instrument_type
    attributes:
      label: Instrument type
      description: >
        What type of instrument is this (e.g. global positioning system, fluorometer)?
        See [L05 SeaDataNet device categories](https://vocab.nerc.ac.uk/collection/L05/current/) for reference.

  - type: dropdown
    id: describes
    attributes:
      label: Does the tool describe a system, or series of instruments?
      description: >
        Does the term describe a 'series', a 'system', an 'individual' instrument, or 'other'? 
        See [this guidance](https://github.com/nvs-vocabs/Guides-and-Resources/blob/main/Instruments%20and%20Sensors.md).
      options:
        - Individual
        - System
        - Series
        - Other

  - type: input
    id: reference
    attributes:
      label: Reference (if applicable)
      description: >
        Citation for the instrument (e.g. Hall and Bumpus, 1937). Leave blank if none.

  - type: input
    id: short_name
    attributes:
      label: Short name
      description: >
        Usually a shortened version of name, or an alternative name.

  - type: input
    id: documentation
    attributes:
      label: Documentation
      description: >
        Link to journal reference, manufacturer data sheet, website, manual, etc.

  - type: textarea
    id: external_mappings
    attributes:
      label: Mapping to external terminologies (optional)
      description: >
        Is your submission related to any existing terms in external resources? Enter one or a list of URIs.

  - type: input
    id: orcid
    attributes:
      label: ORCID (optional)
      description: >
        Enter your ORCID if desired.
